FROM node:16.15.1-alpine

ARG DISCORD_CLIENT_TOKEN
ARG DISCORD_CLIENT_ID
ENV DISCORD_CLIENT_TOKEN=$DISCORD_CLIENT_TOKEN
ENV DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID

COPY . /opt/bot
WORKDIR /opt/bot
RUN npm install
CMD ["node", "index.mjs"]